name: Sync Committed YAML Files to Unreleased Templates

on:
  push:
    paths:
      - '**.yaml'
  workflow_dispatch:

jobs:
  sync-committed-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout nuclei-templates repo
      uses: actions/checkout@v3
      with:
        repository: 'parthmalhotra/nuclei-templates'
        ref: 'master'
        path: 'nuclei-templates'

    - name: Checkout unreleased_templates repo
      uses: actions/checkout@v3
      with:
        repository: 'parthmalhotra/unreleased_templates'
        token: ${{ secrets.GTOKEN }}
        ref: 'main'
        path: 'unreleased_templates'

    - name: Identify Committed YAML files
      id: files
      run: |
        echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | grep '\.yaml$')"

    - name: Sync only Committed YAML files
      if: steps.files.outputs.files != ''
      run: |
        for file in ${{ steps.files.outputs.files }}
        do
          mkdir -p $(dirname unreleased_templates/public/$file) 
          cp nuclei-templates/$file unreleased_templates/public/$file
        done

    - name: Commit and Push changes
      run: |
        cd unreleased_templates
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Sync committed YAML files"
        git push
